### ISSUE TITLE
Hits per seconds..

### ISSUE THREAD

**Issue by clemenko** [jasonhancock/nagios-apache#5]
Not sure if you are still supporting this script. In the pnp4nagios graphs I am seeing total hits in the hits/s graph. Have you seen this?

**Comment by jasonhancock** [comment]
My guess is that it's related to not having installed the [check_apache.cfg](https://github.com/jasonhancock/nagios-apache/blob/master/pnp4nagios/check_commands/check_apache.cfg) file for pnp4nagios. Make sure that file is installed in the correct location, delete the existing .rrd file for your graph and see if it gets re-created with the correct values.

**Comment by clemenko** [comment]
Thanks I will double check that.

**Comment by clemenko** [comment]
Jason, it was permissions on the template files. THANKS

**Comment by PowerPan** [comment]
I have the same problem
in which directory i must put in the check_apache.cfg file?

**Comment by jasonhancock** [comment]
You'll have to locate the `check_commands` directory for your pnp4nagios installation. On EL6 using the pacakges from EPEL, it's `/etc/pnp4nagios/check_commands`, but it could vary based on your distro/installation

```
Copy the pnp4nagios check commands configurations from this repository (pnp4nagios/check_commands) into pnp4nagios' check_commands directory. Using the same package from EPEL as above, this is /etc/pnp4nagios/check_commands. Do this BEFORE configuring the service checks in Nagios otherwise the RRD's will get created with the wrong data types (To fix this, just delete the .rrd files and start over).
```
